config/routes.rb
Rails.application.routes.draw do

  get 'pages/home'
  devise_for :users, controllers: { sessions: 'users/sessions' }
  devise_scope :user do
    get 'sign_in', to: 'users/sessions#new'
    delete 'sign_out', to: 'users/sessions#destroy'
  end
  root to: 'news#index'
  resources :news
  resources :agency_feeds
  resources :agencies
  resources :categories
  resources :users

  post 'save_click', to: 'news#save_click'
  get 'news_report', to: 'news#news_report'
  delete 'delete_all_news', to: 'news#delete_all_news'
  get 'fetch_all_news', to: 'news#fetch_all_news'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/news.rb
require 'rss'
require 'open-uri'

class News < ApplicationRecord
  belongs_to :category
  belongs_to :agency
	validates :news_link, uniqueness: 
	
	def self.fetch_feeds
    categories = Category.all

    categories.each do |cat|
      cat.agency_feeds.each do |agency_feed|
        agency_feed_url = agency_feed.agency_feed_url
        news_rss = RSS::Parser.parse(open(agency_feed_url).read, false).items       
        news_rss.each do |feed|
          # pub_date = DateTime.parse('#{feed.pubDate}')
          News.create(news_title: feed.title, news_description: feed.description, news_publish_date_time: feed.pubDate, news_link: feed.link, click_count: 0,category_id: cat.id, agency_id: agency_feed.agency_id)
        end
      end
    end  
  end
  
  def self.get_news categories_ids = []
    if categories_ids && categories_ids.length > 0
      News.where("category_id in (#{categories_ids.join(',')})").order(news_publish_date_time: :desc)
    else
      News.order(news_publish_date_time: :desc)
    end
  end

end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :set_news, only: [:show, :edit, :update, :destroy, :save_click]
  before_action :authenticate_user!, only: [:show, :edit, :update, :destroy, :create, :updated, :news_report, :delete_all_news, :fetch_all_news]
  skip_before_action :authenticate_user!, only: [:save_click, :index]

  # GET /news
  # GET /news.json
  def index
    @category_ids = params[:categories]
    
    # Call this to fetch news from rss sources and store into db.
    # Uncomment "News.fetch_feeds" if background scheduling does not work.
    # News.fetch_feeds
    ##################

    @categories = Category.all
    @all_news = News.get_news @category_ids
  end

  # GET /news/1
  # GET /news/1.json
  def show
  end

  # GET /news/new
  def new
    @news = News.new
  end

  # GET /news/1/edit
  def edit
  end

  # POST /news
  # POST /news.json
  def create
    @news = News.new(news_params)

    respond_to do |format|
      if @news.save
        format.html { redirect_to @news, notice: 'News was successfully created.' }
        format.json { render :show, status: :created, location: @news }
      else
        format.html { render :new }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news/1
  # PATCH/PUT /news/1.json
  def update
    respond_to do |format|
      if @news.update(news_params)
        format.html { redirect_to @news, notice: 'News was successfully updated.' }
        format.json { render :show, status: :ok, location: @news }
      else
        format.html { render :edit }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    @news.destroy
    respond_to do |format|
      format.html { redirect_to news_index_url, notice: 'News was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def save_click
    puts params[:id]
    if @news.present?
      count =  @news.click_count.to_i + 1
      @news.update(click_count: count)
    end

    respond_to do |format|
      format.js
    end
  end

  # Method to manage news and view click report
  def news_report
    @all_news = News.order(click_count: :desc)
    @show_report = true
    render :template => 'news/index'
  end

  # Delete all news
  def delete_all_news
    News.delete_all
    @show_report = true
    @all_news = News.all
    render :template => 'news/index'
  end

  def fetch_all_news
    News.fetch_feeds
    @show_report = true
    @all_news = News.all
    render :template => 'news/index'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news
      @news = News.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def news_params
      params.require(:news).permit(:news_title, :news_description, :news_publish_date_time, :news_link, :click_count, :category_id, :agency_id)
    end
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/news/_form.html.erb
<%= form_with(model: news, local: true) do |form| %>
  <% if news.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(news.errors.count, "error") %> prohibited this news from being saved:</h2>

      <ul>
        <% news.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :news_title %>
    <%= form.text_field :news_title, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :news_description %>
    <%= form.text_area :news_description, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :news_publish_date_time %>
    <%= form.datetime_select :news_publish_date_time, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :news_link %>
    <%= form.text_area :news_link, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :click_count %>
    <%= form.text_field :click_count, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.select(:category_id, Category.all.collect { |p| [ p.category_title, p.id ] }, { include_blank: "-Select Category-" }, html_options = {class: "form-control", required: true}) %>
    <%= form.label :category_id %>
  </div>

  <div class="field">
    <%= form.select(:agency_id, Agency.all.collect { |p| [ p.agency_name, p.id ] }, { include_blank: "-Select Agency-" }, html_options = {class: "form-control", required: true}) %>  
    <%= form.label :agency_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/news/edit.html.erb
<h1>Editing News</h1>

<%= render 'form', news: @news %>

<%= link_to 'Show', @news %> |
<%= link_to 'Back', news_index_path %>

app/views/news/index.html.erb
<div class="news-feeds">  
  <% if user_signed_in? && @show_report.present? %>
    <span class="delete-news"><%= link_to 'Delete All News', delete_all_news_path, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-submit" %></span>
    <span class="delete-news"><%= link_to 'Fetch News from RSS feeds', fetch_all_news_path, class: "btn btn-submit" %></span>
  <% end %>
  <h1>News</h1>
  <% if @all_news.present? %>
    <% @all_news.each do |news| %>
      <div class="news-item" id="<%= news.id %>">
        <h4 class="news-title"><%= link_to news.news_title, news.news_link, target: :_blank, class: "news-link" %></h4>
        <p class="news-desc"><%= news.news_description.html_safe %></p>
        <span class="news-pub"><%= news.news_publish_date_time %></span>
        <% if user_signed_in? && @show_report.present? %>
          <br/>
          <span class="news-clicks">Number of clicks: <%= news.click_count %></span>
        <% end %>
      </div>
    <% end %>
  <% else %>
    <div class="news-item">
      <p class="news-desc">No News present!</p>
    </div>
  <% end %>
</div>

app/views/news/new.html.erb
<h1>New News</h1>

<%= render 'form', news: @news %>

<%= link_to 'Back', news_index_path %>

app/views/news/show.html.erb
<p>
  <strong>News title:</strong>
  <%= @news.news_title %>
</p>

<p>
  <strong>News description:</strong>
  <%= @news.news_description %>
</p>

<p>
  <strong>News publish date time:</strong>
  <%= @news.news_publish_date_time %>
</p>

<p>
  <strong>News link:</strong>
  <%= @news.news_link %>
</p>

<p>
  <strong>Click count:</strong>
  <%= @news.click_count %>
</p>

<p>
  <strong>Category:</strong>
  <%= @news.category.category_title %>
</p>

<p>
  <strong>Agency:</strong>
  <%= @news.agency.agency_name %>
</p>

<%= link_to 'Edit', edit_news_path(@news) %> |
<%= link_to 'Back', news_index_path %>