config/routes.rb
Rails.application.routes.draw do

  get 'pages/home'
  devise_for :users, controllers: { sessions: 'users/sessions' }
  devise_scope :user do
    get 'sign_in', to: 'users/sessions#new'
    delete 'sign_out', to: 'users/sessions#destroy'
  end
  root to: 'news#index'
  resources :news
  resources :agency_feeds
  resources :agencies
  resources :categories
  resources :users

  post 'save_click', to: 'news#save_click'
  get 'news_report', to: 'news#news_report'
  delete 'delete_all_news', to: 'news#delete_all_news'
  get 'fetch_all_news', to: 'news#fetch_all_news'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/agency.rb
class Agency < ApplicationRecord
  has_many :news
  has_many :agency_feeds
end

app/controllers/agencies_controller.rb
class AgenciesController < ApplicationController
  before_action :set_agency, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /agencies
  # GET /agencies.json
  def index
    @agencies = Agency.all
  end

  # GET /agencies/1
  # GET /agencies/1.json
  def show
  end

  # GET /agencies/new
  def new
    @agency = Agency.new
  end

  # GET /agencies/1/edit
  def edit
  end

  # POST /agencies
  # POST /agencies.json
  def create
    @agency = Agency.new(agency_params)

    respond_to do |format|
      if @agency.save
        format.html { redirect_to @agency, notice: 'Agency was successfully created.' }
        format.json { render :show, status: :created, location: @agency }
      else
        format.html { render :new }
        format.json { render json: @agency.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /agencies/1
  # PATCH/PUT /agencies/1.json
  def update
    respond_to do |format|
      if @agency.update(agency_params)
        format.html { redirect_to @agency, notice: 'Agency was successfully updated.' }
        format.json { render :show, status: :ok, location: @agency }
      else
        format.html { render :edit }
        format.json { render json: @agency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /agencies/1
  # DELETE /agencies/1.json
  def destroy
    @agency.destroy
    respond_to do |format|
      format.html { redirect_to agencies_url, notice: 'Agency was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_agency
      @agency = Agency.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def agency_params
      params.require(:agency).permit(:agency_name, :agency_logo_path)
    end
end

app/helpers/agencies_helper.rb
module AgenciesHelper
end

app/views/agencies/_form.html.erb
<%= form_with(model: agency, local: true) do |form| %>
  <% if agency.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(agency.errors.count, "error") %> prohibited this agency from being saved:</h2>

      <ul>
        <% agency.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :agency_name %>
    <%= form.text_field :agency_name, class: "form-control", required: true %>
  </div>

  <div class="form-group">
    <%= form.label :agency_logo_path %>
    <%= form.text_area :agency_logo_path, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/agencies/edit.html.erb
<h1>Editing Agency</h1>

<%= render 'form', agency: @agency %>

<%= link_to 'Show', @agency %> |
<%= link_to 'Back', agencies_path %>

app/views/agencies/index.html.erb
<h1>Agencies</h1>

<table>
  <thead>
    <tr>
      <th>S. No.</th>
      <th>Agency name</th>
      <th>Agency logo path</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @agencies.each_with_index do |agency, i| %>
      <tr>
        <td><%= i+1 %></td>
        <td><%= agency.agency_name %></td>
        <td><%= agency.agency_logo_path %></td>
        <td><%= link_to 'Show', agency %></td>
        <td><%= link_to 'Edit', edit_agency_path(agency) %></td>
        <td><%= link_to 'Destroy', agency, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Agency', new_agency_path %>

app/views/agencies/new.html.erb
<h1>New Agency</h1>

<%= render 'form', agency: @agency %>

<%= link_to 'Back', agencies_path %>

app/views/agencies/show.html.erb
<p>
  <strong>Agency name:</strong>
  <%= @agency.agency_name %>
</p>

<p>
  <strong>Agency logo path:</strong>
  <%= @agency.agency_logo_path %>
</p>

<%= link_to 'Edit', edit_agency_path(@agency) %> |
<%= link_to 'Back', agencies_path %>