config/routes.rb
Rails.application.routes.draw do

  get 'pages/home'
  devise_for :users, controllers: { sessions: 'users/sessions' }
  devise_scope :user do
    get 'sign_in', to: 'users/sessions#new'
    delete 'sign_out', to: 'users/sessions#destroy'
  end
  root to: 'news#index'
  resources :news
  resources :agency_feeds
  resources :agencies
  resources :categories
  resources :users

  post 'save_click', to: 'news#save_click'
  get 'news_report', to: 'news#news_report'
  delete 'delete_all_news', to: 'news#delete_all_news'
  get 'fetch_all_news', to: 'news#fetch_all_news'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/agency_feed.rb
class AgencyFeed < ApplicationRecord
  belongs_to :category
  belongs_to :agency
end

app/controllers/agency_feeds_controller.rb
class AgencyFeedsController < ApplicationController
  before_action :set_agency_feed, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /agency_feeds
  # GET /agency_feeds.json
  def index
    @agency_feeds = AgencyFeed.all
  end

  # GET /agency_feeds/1
  # GET /agency_feeds/1.json
  def show
  end

  # GET /agency_feeds/new
  def new
    @agency_feed = AgencyFeed.new
  end

  # GET /agency_feeds/1/edit
  def edit
  end

  # POST /agency_feeds
  # POST /agency_feeds.json
  def create
    @agency_feed = AgencyFeed.new(agency_feed_params)

    respond_to do |format|
      if @agency_feed.save
        format.html { redirect_to @agency_feed, notice: 'Agency feed was successfully created.' }
        format.json { render :show, status: :created, location: @agency_feed }
      else
        format.html { render :new }
        format.json { render json: @agency_feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /agency_feeds/1
  # PATCH/PUT /agency_feeds/1.json
  def update
    respond_to do |format|
      if @agency_feed.update(agency_feed_params)
        format.html { redirect_to @agency_feed, notice: 'Agency feed was successfully updated.' }
        format.json { render :show, status: :ok, location: @agency_feed }
      else
        format.html { render :edit }
        format.json { render json: @agency_feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /agency_feeds/1
  # DELETE /agency_feeds/1.json
  def destroy
    @agency_feed.destroy
    respond_to do |format|
      format.html { redirect_to agency_feeds_url, notice: 'Agency feed was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_agency_feed
      @agency_feed = AgencyFeed.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def agency_feed_params
      params.require(:agency_feed).permit(:agency_feed_url, :agency_id, :category_id)
    end
end

app/helpers/agency_feeds_helper.rb
module AgencyFeedsHelper
end

app/views/agency_feeds/_form.html.erb
<%= form_with(model: agency_feed, local: true) do |form| %>
  <% if agency_feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(agency_feed.errors.count, "error") %> prohibited this agency_feed from being saved:</h2>

      <ul>
        <% agency_feed.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :agency_feed_url %>
    <%= form.text_area :agency_feed_url, class: "form-control", required: true %>
  </div>

  <div class="form-group">
    <%= form.select(:category_id, Category.all.collect { |p| [ p.category_title, p.id ] }, { include_blank: "-Select Category-" }, html_options = {class: "form-control", required: true}) %>
    <%= form.label :category_id %>
  </div>

  <div class="form-group">
    <%= form.select(:agency_id, Agency.all.collect { |p| [ p.agency_name, p.id ] }, { include_blank: "-Select Agency-" }, html_options = {class: "form-control", required: true}) %>  
    <%= form.label :agency_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/agency_feeds/edit.html.erb
<h1>Editing Agency Feed</h1>

<%= render 'form', agency_feed: @agency_feed %>

<%= link_to 'Show', @agency_feed %> |
<%= link_to 'Back', agency_feeds_path %>

app/views/agency_feeds/index.html.erb
<h1>Agency Feeds</h1>

<table>
  <thead>
    <tr>
      <th>S. NO.</th>
      <th>Agency feed url</th>
      <th>Agency</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @agency_feeds.each_with_index do |agency_feed, i| %>
      <tr>
        <td><%= i+1 %></td>
        <td><%= agency_feed.agency_feed_url %></td>
        <td><%= agency_feed.agency.agency_name %></td>
        <td><%= agency_feed.category.category_title %></td>
        <td><%= link_to 'Show', agency_feed %></td>
        <td><%= link_to 'Edit', edit_agency_feed_path(agency_feed) %></td>
        <td><%= link_to 'Destroy', agency_feed, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Agency Feed', new_agency_feed_path %>

app/views/agency_feeds/new.html.erb
<h1>New Agency Feed</h1>

<%= render 'form', agency_feed: @agency_feed %>

<%= link_to 'Back', agency_feeds_path %>

app/views/agency_feeds/show.html.erb
<p>
  <strong>Agency feed url:</strong>
  <%= @agency_feed.agency_feed_url %>
</p>

<p>
  <strong>Agency:</strong>
  <%= @agency_feed.agency.agency_name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @agency_feed.category.category_title %>
</p>

<%= link_to 'Edit', edit_agency_feed_path(@agency_feed) %> |
<%= link_to 'Back', agency_feeds_path %>